name: nrfutil

on:
  workflow_dispatch:

jobs:
  nrfutil:
    runs-on: ubuntu-22.04
    env:
        NRFUTIL_LOG: "trace"
        SDK_BRANCH: v2.9-branch
        TOOLCHAIN_VERSION: v2.9.0
    steps:
      - run: |
            # sudo apt-get update
            # sudo apt-get install -y libunistring5
            wget https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil
            mv nrfutil /usr/local/bin
            chmod +x /usr/local/bin/nrfutil
            nrfutil install toolchain-manager
            nrfutil toolchain-manager install --ncs-version ${{ env.TOOLCHAIN_VERSION }}
            nrfutil toolchain-manager list

            # launch doesn't work in CI, export instead
            nrfutil toolchain-manager env --as-script > export_env.sh
            source export_env.sh

            west init -m https://github.com/nrfconnect/sdk-nrf --mr ${{ env.SDK_BRANCH }} .
            west update --narrow -o=--depth=1

            cd ${GITHUB_WORKSPACE}
            echo "Listing contents of GITHUB_WORKSPACE:"
            ls -la "${GITHUB_WORKSPACE}"

            cd nrf/applications/nrf_desktop
            
            west build -b nrf54l15dk/nrf54l15/cpuapp -p=auto

      - name: Build nrf_desktop application for CodeQL
        if: ${{ matrix.language == 'c-cpp' && matrix.build-mode == 'manual' }}
        run: |
          echo "Building nrf_desktop application for CodeQL..."
        
          # --- 調試訊息：印出 PATH 變數 (保留用於診斷) ---
          echo "Current PATH before west build:"
          echo "$PATH"
          echo "Attempting to find west command:"
          which west || echo "west command not found in PATH"
          west --version || echo "west --version failed"
          # --- 調試訊息結束 ---

          # 定義 CodeQL 資料庫路徑
          # 這個路徑是由 github/codeql-action/init 步驟設定的
          CODEQL_DATABASE_PATH="/home/runner/work/_temp/codeql_databases/${{ matrix.language }}" 

          # 您的應用程式目錄設定
          # 請根據您 ci.yml 中的實際路徑和 actions/checkout 的 path 參數來確認
          APP_DIR="${GITHUB_WORKSPACE}/zephyr-workspace/nrf/applications/nrf_desktop" 

          if [ ! -d "$APP_DIR" ]; then
            echo "Error: nrf_desktop application directory not found at $APP_DIR. Please adjust APP_DIR variable in the YAML."
            ls -R "${GITHUB_WORKSPACE}/zephyr-workspace" # 加入調試訊息
            exit 1
          fi
        
          # 進入應用程式目錄
          cd "$APP_DIR"

          # ----------------------------------------------------------------------------------
          # 這是關鍵的修正：使用 'codeql database trace-command' 包裹 west build
          # ----------------------------------------------------------------------------------
          echo "Executing west build wrapped by CodeQL trace-command..."
          codeql database trace-command "${CODEQL_DATABASE_PATH}" \
            west build -b nrf54l15dk/nrf54l15/cpuapp --pristine auto --build-dir build_codeql
        
          echo "nrf_desktop build for CodeQL complete."
