name: nrfutil

on:
  workflow_dispatch:

jobs:
  nrfutil:
    runs-on: ubuntu-22.04
    env:
        NRFUTIL_LOG: "trace"
        SDK_BRANCH: v2.9-branch
        TOOLCHAIN_VERSION: v2.9.0
    steps:
      - run: |
            # sudo apt-get update
            # sudo apt-get install -y libunistring5
            wget https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil
            mv nrfutil /usr/local/bin
            chmod +x /usr/local/bin/nrfutil
            nrfutil install toolchain-manager
            nrfutil toolchain-manager install --ncs-version ${{ env.TOOLCHAIN_VERSION }}
            nrfutil toolchain-manager list

            # launch doesn't work in CI, export instead
            nrfutil toolchain-manager env --as-script > export_env.sh
            source export_env.sh

            west init -m https://github.com/nrfconnect/sdk-nrf --mr ${{ env.SDK_BRANCH }} .
            west update --narrow -o=--depth=1

            cd ${GITHUB_WORKSPACE}
            echo "Listing contents of GITHUB_WORKSPACE:"
            ls -la "${GITHUB_WORKSPACE}"

            cd nrf/applications/nrf_desktop
            
            west build -b nrf54l15dk/nrf54l15/cpuapp -p=auto

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp

      - name: Perform CodeQL Analysis # CodeQL 會自動監控上一步的構建過程
        uses: github/codeql-action/analyze@v3
