name: CodeQL Analysis for nrf_desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜執行

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-22.04

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        ecr: false

    # 1. 檢查出程式碼
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. 安裝 Zephyr 和 nRF Connect SDK 依賴
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ccache \
          cmake \
          file \
          g++-multilib \
          gcc \
          gcc-multilib \
          git \
          gperf \
          make \
          ninja-build \
          python3-venv \
          wget \
          xz-utils

    # 3. 安裝 Zephyr SDK
    - name: Install Zephyr SDK
      run: |
        wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64_minimal.tar.xz
        mkdir -p /opt/toolchains
        tar xf zephyr-sdk-0.16.4_linux-x86_64_minimal.tar.xz -C /opt/toolchains
        /opt/toolchains/zephyr-sdk-0.16.4/setup.sh -c -t arm-zephyr-eabi
        rm zephyr-sdk-0.16.4_linux-x86_64_minimal.tar.xz
      env:
        CMAKE_PREFIX_PATH: /opt/toolchains

    # 4. 設置 Python 虛擬環境並安裝 west
    - name: Set up Python virtual environment
      run: |
        python3 -m venv /venv
        . /venv/bin/activate
        pip install --no-cache-dir west==1.2.0

    # 5. 初始化 Zephyr 工作區
    - name: Initialize Zephyr workspace
      run: |
        . /venv/bin/activate
        west init -l .
        west update --narrow -o=--depth=1
      working-directory: ${{ github.workspace }}

    # 6. 安裝 Python 依賴
    - name: Install Python dependencies
      run: |
        . /venv/bin/activate
        pip install -r zephyr/scripts/requirements.txt
      working-directory: ${{ github.workspace }}

    # 7. 初始化 CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp
        queries: security-and-quality

    # 8. 編譯 nrf_desktop 專案
    - name: Build nrf_desktop
      run: |
        . /venv/bin/activate
        west build -b nrf54l15dk_nrf54l15_cpuapp -p always applications/nrf_desktop
      working-directory: ${{ github.workspace }}

    # 9. 執行 CodeQL 分析
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "codeql/cpp"